-- 코드를 작성해주세요
SELECT 
    t.YEAR,
    t.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN (SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
      FROM ECOLI_DATA
      GROUP BY YEAR
     ) t 
    ON YEAR(e.DIFFERENTIATION_DATE) = t.YEAR
ORDER BY t.YEAR, YEAR_DEV;