-- 코드를 작성해주세요
SELECT
    f.ID,
    n.FISH_NAME,
    t.MAX_LENGTH AS LENGTH
FROM FISH_INFO f
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE
     ) t ON f.FISH_TYPE = t.FISH_TYPE AND f.LENGTH = t.MAX_LENGTH
JOIN FISH_NAME_INFO n
    ON f.FISH_TYPE = n.FISH_TYPE
ORDER BY f.ID;