-- 코드를 입력하세요
SELECT
    b.CATEGORY,
    SUM(s.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES s
    ON b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE > '2021-12-31' AND s.SALES_DATE < '2022-02-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;