-- 코드를 작성해주세요
SELECT
    COUNT(f.ID) AS FISH_COUNT,
    MAX(f.LENGTH) AS MAX_LENGTH,
    f.FISH_TYPE
FROM FISH_INFO f
JOIN (SELECT FISH_TYPE, AVG(LENGTH) AS AVG_LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE
     ) t ON f.FISH_TYPE = t.FISH_TYPE
WHERE t.AVG_LENGTH >= 33
GROUP BY f.FISH_TYPE
ORDER BY f.FISH_TYPE;